package RunnerGui

import java.io.File
import java.io.IOException
import java.math.BigDecimal
import java.util.{List => JList, ArrayList => JAList}
import java.util.{Date, Locale}
import java.text.DateFormat
import java.text.DateFormat._

import javax.xml.bind.JAXBContext
import javax.xml.bind.JAXBElement
import javax.xml.bind.JAXBException
import javax.xml.bind.Marshaller
import javax.xml.bind.Unmarshaller

import scala.collection.JavaConversions._
import java.awt.Dimension
import javax.swing._

import scala.swing.MainFrame
import RunnerGui._
import com.google.inject.Guice

import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel


// import java content classes generated by binding compiler
// import tcx._

object GuiTcx {
  val titlePrefix = "OhTop Runner"

  def main(args: Array[String]): Unit = {
               // create a JAXBContext capable of handling classes generated into
            // the primer.po package
    try{
    	SwingUtilities.invokeLater(
      
    	new Runnable {
        def run = {
          UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel)
          val frame = new MainFrame
          frame.title = titlePrefix
          
          
          val injector = Guice.createInjector(new GuiceModule)
          
          val scalaGui = injector.getInstance(classOf[ScalaGui])
          scalaGui.init(frame)
          
          frame.size = new Dimension(600, 600)
          frame.pack
          frame.visible = true
        }
      }
    )           

}
   // catch ()
  }
}